spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost/~/database
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
server:
  servlet:
    session:
      timeout: 30m
